version: 0.0
os: linux
files:
  - source: /UI-devias  # Adjust the path to your built frontend
    destination: /var/www/html/frontend
  - source: /api  # Adjust the path your built/packaged backend
    destination: /var/www/html/backend 
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300  
  ApplicationStart:
    - location: scripts/start_services.sh
      timeout: 300
